### PR TITLE
Users/ka05/opencv update 343

### PR DESCRIPTION
**Pull request by ka05**
This PR updates OpenCV from version 340 to 343 resolving Issue #39. 

I apologize for the size of this PR as many files were replaced for the openCVLibrary module update. Actual code changes are limited to the gradle files.

### CODE REVIEW

**Comment by Omid-SH** [comment]
I had the same issue with the latest update of the code and I tried this PR and it worked completely correct.  Thanks :)

**Comment by klaszlo8207** [comment]
Any news on this? Can somebody apply the PR?

**Comment by hannesa2** [comment]
> Any news on this? Can somebody apply the PR?

Give it a try https://github.com/hannesa2/LiveEdgeDetection it's currently on OpenCV 4.4.0

**Comment by klaszlo8207** [comment]
> 
> 
> > Any news on this? Can somebody apply the PR?
> 
> Give it a try https://github.com/hannesa2/LiveEdgeDetection it's currently on OpenCV 4.4.0

Tried that too, with a lot of other errors :D

**Comment by Kaushik-Ravibaskar** [comment]
Is the procedure to apply this PR correct?
com.github.adityaarora1:LiveEdgeDetection:PR42-SNAPSHOT
Can someone confirm this?

**Pull request merged**
