### PR TITLE
Patch for improved edge detection

### PR DESCRIPTION
**Pull request by Udayraj123**
Just OTSU/Binary thresholding is not enough.
Following steps drastically improve the edge detection.
1. First blur and normalize the image for uniformity,
2. Truncate light-gray to white and normalize,
3. Apply canny edge detection,
4. Cutoff weak edges,
5. Apply closing(morphology), then proceed to finding contours.
Also converting the contours to their Convex Hulls will remove minor nuances in the contour.

### CODE REVIEW

**Comment by hayden-accolade** [comment]
This is not working for me. I'm getting:
```
E/art: No implementation found for void org.opencv.imgproc.Imgproc.Canny_4(long, long, double, double) (tried Java_org_opencv_imgproc_Imgproc_Canny_14 and Java_org_opencv_imgproc_Imgproc_Canny_14__JJDD)
```
Which is strange because (as far as I can tell) the implementation _does_ exist. 

Would you know what the problem with that is?

**Comment by Udayraj123** [comment]
Not sure. It should run ideally. What version of OpenCV and Android studio are you using?

**Comment by hayden-accolade** [comment]
Android Studio 3.4.1 and OpenCV 3.4.0 (included in this repository)

I downgraded to OpenCV 3.1.0 in a fork of this repository and that definitely seemed to work.

Thanks!

**Comment by Udayraj123** [comment]
Great! Can you verify the page contours are in a detected much better way now?

**Comment by hayden-accolade** [comment]
Yes, it's working a **lot** better than it did before!

**Comment by Udayraj123** [comment]
Are you a contributor? (Will you be able to get the pull request accepted?)

**Comment by hayden-accolade** [comment]
No :( Sorry about that!

**Comment by Udayraj123** [comment]
Btw I've made my own edge detection app for OMR Sheet Cropping(Which works even better as it is fully configurable within the app!). Can you please check if it builds and runs on your machine?
https://github.com/Udayraj123/AndroidOMRChecker

P.S. ignore the lower-half of the Readme(It's under updation yet)

**Comment by Udayraj123** [comment]
I guess tagging shall help.
@adityaarora1 can you checkout the PR

**Comment by adityaarora1** [comment]
Hi

Sure I will do that

Regards
Aditya

**Comment by Udayraj123** [comment]
It's a basic version though, by now I've gotten even more improvements on it. But review this one first!

**Comment by Udayraj123** [comment]
Hi @adityaarora1, hope everything is fine. Any comments on the PR?

**Comment by zakblacki** [comment]
Sometimes the image saved get blurry because of the autofocus wasn't ready Is there anyway to make constraint for the algorithm to detect OCR image ?

**Comment by rohitgarg29** [comment]
@Udayraj123 i am trying to use your library for improved edge detection, after setting the frame using Polygon view, I hit Ok, edge are cut off. Can you please help with the same?

**Pull request merged**
